"""add username field in message model

Revision ID: 6749e7c7bb31
Revises: caf2e5913059
Create Date: 2025-11-02 12:03:02.115904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6749e7c7bb31'
down_revision: Union[str, Sequence[str], None] = 'caf2e5913059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_username', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_username')
    # ### end Alembic commands ###
