"""modify room model

Revision ID: 85ddc8e3bc0c
Revises: 
Create Date: 2025-10-11 00:27:49.497914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ddc8e3bc0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('room_type', sa.VARCHAR(length=20), nullable=False))
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_active')
    op.drop_column('rooms', 'room_type')
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
